//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xander.PasswordValidator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WordLists {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordLists() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xander.PasswordValidator.Resources.WordLists", typeof(WordLists).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2013 Colin Angus Mackay
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to 
        ///deal in the Software without restriction, including without limitation the 
        ///rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
        ///sell copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string @__License_Information__ {
            get {
                return ResourceManager.GetString("__License_Information__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaren
        ///aarika
        ///aaron
        ///abagael
        ///abagail
        ///abbe
        ///abbey
        ///abbi
        ///abbie
        ///abby
        ///abbye
        ///abigael
        ///abigail
        ///abigale
        ///abra
        ///acacia
        ///ada
        ///adah
        ///adaline
        ///adam
        ///adan
        ///adara
        ///adda
        ///addi
        ///addia
        ///addie
        ///addy
        ///adel
        ///adela
        ///adelaida
        ///adelaide
        ///adele
        ///adelheid
        ///adelia
        ///adelice
        ///adelina
        ///adelind
        ///adeline
        ///adell
        ///adella
        ///adelle
        ///adena
        ///adey
        ///adi
        ///adiana
        ///adina
        ///adora
        ///adore
        ///adoree
        ///adorne
        ///adrea
        ///adria
        ///adriaens
        ///adrian
        ///adriana
        ///adriane
        ///adrianna
        ///adrianne
        ///adrien
        ///adriena
        ///adriene
        ///adrienne
        ///aeriel
        ///aeriela
        ///aeriell
        ///afton
        ///ag
        ///agace
        ///agata
        ///agatha
        ///agathe
        ///aggi
        ///aggie
        ///aggy
        ///agna
        ///agnella
        ///agnes
        ///agne [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaron
        ///ab
        ///abba
        ///abbe
        ///abbey
        ///abbie
        ///abbot
        ///abbott
        ///abby
        ///abdel
        ///abdul
        ///abe
        ///abel
        ///abelard
        ///abeu
        ///abey
        ///abie
        ///abner
        ///abraham
        ///abrahan
        ///abram
        ///abramo
        ///abran
        ///ad
        ///adair
        ///adam
        ///adamo
        ///adams
        ///adan
        ///addie
        ///addison
        ///addy
        ///ade
        ///adelbert
        ///adham
        ///adlai
        ///adler
        ///ado
        ///adolf
        ///adolph
        ///adolphe
        ///adolpho
        ///adolphus
        ///adrian
        ///adriano
        ///adrien
        ///agosto
        ///aguie
        ///aguistin
        ///aguste
        ///agustin
        ///aharon
        ///ahmad
        ///ahmed
        ///ailbert
        ///akim
        ///aksel
        ///al
        ///alain
        ///alair
        ///alan
        ///aland
        ///alano
        ///alanson
        ///alard
        ///alaric
        ///alasdair
        ///alastair
        ///alasteir
        ///alaster
        ///alberik
        ///albert
        ///alberto
        ///albie
        ///albrecht
        ///alden
        ///aldin
        ///aldis
        ///aldo
        ///aldon
        ///ald [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456
        ///password
        ///12345678
        ///1234
        ///pussy
        ///12345
        ///dragon
        ///qwerty
        ///696969
        ///mustang
        ///letmein
        ///baseball
        ///master
        ///michael
        ///football
        ///shadow
        ///monkey
        ///abc123
        ///pass
        ///fuckme
        ///6969
        ///jordan
        ///harley
        ///ranger
        ///iwantu
        ///jennifer
        ///hunter
        ///fuck
        ///2000
        ///test
        ///batman
        ///trustno1
        ///thomas
        ///tigger
        ///robert
        ///access
        ///love
        ///buster
        ///1234567
        ///soccer
        ///hockey
        ///killer
        ///george
        ///sexy
        ///andrew
        ///charlie
        ///superman
        ///asshole
        ///fuckyou
        ///dallas
        ///jessica
        ///panties
        ///pepper
        ///1111
        ///austin
        ///william
        ///daniel
        ///golfer
        ///summer
        ///heather
        ///hammer
        ///yankees
        ///joshua
        ///maggie
        ///biteme
        ///enter
        ///ashley
        ///thunder
        ///cowboy
        ///silver
        ///richard
        ///fucker
        ///o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MostCommon500Passwords {
            get {
                return ResourceManager.GetString("MostCommon500Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaberg
        ///Aaron
        ///Abarca
        ///Abbate
        ///Abbess
        ///Abbott
        ///Abbratozzato
        ///Abdelnour
        ///Abderrazzaq
        ///Abdollah
        ///Abdous
        ///Abdullah
        ///Abdulrazak
        ///Abe
        ///Abel
        ///Abelmann
        ///Abelson
        ///Abernathy
        ///Abnet
        ///Abraham
        ///Abraham-Scalapino
        ///Abrams
        ///Abramson
        ///Abromson-Leeman
        ///Aburdene
        ///Acambages
        ///Accardo
        ///Accomazzi
        ///Achacoso
        ///Acker
        ///Ackerly
        ///Ackerman
        ///Acus
        ///Adair
        ///Adam
        ///Adame
        ///Adams
        ///Adamson
        ///Addison
        ///Ade
        ///Adelson
        ///Adelstein
        ///Adibe
        ///Adicho
        ///Adiele
        ///Adler
        ///Adolph
        ///Adorno
        ///Adourian
        ///Adrian-Haberly
        ///Affricano
        ///Africa
        ///Aftergut
        ///Afzal-Khan
        ///Agee
        ///Aghayan
        ///Agostinelli
        ///Agrawal
        ///Agren
        ///Agresti
        ///Agro&apos;
        ///Agterberg
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
    }
}
